# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [master]
    # paths:
    #   - 'src/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub API [Contributors]
        ### The first request is for building the cache. It will not return anything.
        uses: octokit/request-action@v2.0.2
        with:
          route: GET /repos/:repository/stats/contributors
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1.4.2
      - uses: actions/checkout@master
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Compile WASM
        run: wasm-pack build
        working-directory: ./wasm
      - name: Install
        run: yarn
      - name: GitHub API [Contributors]
        uses: octokit/request-action@v2.0.2
        id: get_contributors
        with:
          route: GET /repos/:repository/stats/contributors
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save Contributors to a file
        shell: bash
        run: echo -e ${{ toJSON(steps.get_contributors.outputs.data) }} > src/data/contributors.json
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automatic Deploy" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
